In [1]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
# 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [5]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [6]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [4]:
# 독립변수, 종속변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [10]:
# 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [11]:
# 데이터로 모델을 학습
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1501 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1497 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1502 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1492 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1503 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1494 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1492 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1490 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1492 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1492 - accuracy: 0.9800


In [18]:
# 모델을 이용
print(model.predict(독립[20:25 ]))
print(종속[20:25])

[[9.9762696e-01 2.3729638e-03 1.3248302e-07]
 [9.9851269e-01 1.4871751e-03 1.1975256e-07]
 [9.9973184e-01 2.6818481e-04 9.9858433e-09]
 [9.9058658e-01 9.4110509e-03 2.3540263e-06]
 [9.9196458e-01 8.0341157e-03 1.3380802e-06]]
    품종_setosa  품종_versicolor  품종_virginica
20          1              0             0
21          1              0             0
22          1              0             0
23          1              0             0
24          1              0             0


In [20]:
# Weights & bias 출력
print(model.get_weights())

[array([[ 0.98114115,  0.10882274, -1.1499288 ],
       [ 2.1998541 ,  0.08147203, -1.0686225 ],
       [-4.189823  , -0.6805303 ,  1.0081131 ],
       [-4.5646253 , -1.5269779 ,  1.829848  ]], dtype=float32), array([ 1.761797 ,  1.0602483, -1.5674266], dtype=float32)]
