In [7]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [8]:
# 과거의 데이터 준비

파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [9]:
# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴 [['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [11]:
# 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation = 'swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [38]:
model.summary()

Model: "functional_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [63]:
# 데이터로 모델을 학습하기
# model.fit(독립, 종속, epochs=100000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 27.9892
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 29.2610
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 26.9410
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 28.2239
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 28.7836
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 27.2776
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 27.4986
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 28.7976
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 26.7100
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 27.1066


In [39]:
# 모델을 이용합니다.
print(model.predict(독립[0:5]))

[[26.76333 ]
 [23.381538]
 [27.798117]
 [27.59981 ]
 [26.635416]]


In [40]:
종속[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [ ]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.0924654 ],
        [ 0.04930371],
        [-0.02615133],
        [ 2.6586483 ],
        [-0.47853842],
        [ 5.3555503 ],
        [-0.01147587],
        [-1.0263922 ],
        [ 0.18970141],
        [-0.01130235],
        [-0.48243785],
        [ 0.01309918],
        [-0.4593827 ]], dtype=float32), array([6.1361566], dtype=float32)]

In [66]:
# 과거의 데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [67]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [73]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [72]:
# 독립변수, 종속변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor',
       '품종_virginica']]
print(독립.shape, 종속.shape)

KeyError: ignored

In [65]:
# 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation = 'swish')(X)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
H = tf.keras.layers.Dense(8, activation = 'swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [74]:
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [64]:
# 데이터로 모델을 학습
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 23.3202
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8492
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9362
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 24.6973
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 22.6384
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8257
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 23.1541
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 22.7419
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.8573
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 22.5240


In [ ]:
# 모델을 이용
print(model.predict(독립[20:25 ]))
print(종속[20:25])

[[9.9762696e-01 2.3729638e-03 1.3248302e-07]
 [9.9851269e-01 1.4871751e-03 1.1975256e-07]
 [9.9973184e-01 2.6818481e-04 9.9858433e-09]
 [9.9058658e-01 9.4110509e-03 2.3540263e-06]
 [9.9196458e-01 8.0341157e-03 1.3380802e-06]]
    품종_setosa  품종_versicolor  품종_virginica
20          1              0             0
21          1              0             0
22          1              0             0
23          1              0             0
24          1              0             0


In [ ]:
# Weights & bias 출력
print(model.get_weights())

[array([[ 0.98114115,  0.10882274, -1.1499288 ],
       [ 2.1998541 ,  0.08147203, -1.0686225 ],
       [-4.189823  , -0.6805303 ,  1.0081131 ],
       [-4.5646253 , -1.5269779 ,  1.829848  ]], dtype=float32), array([ 1.761797 ,  1.0602483, -1.5674266], dtype=float32)]
